services:
  api-container:
    image: alpine:latest
    platform: linux/arm64
    container_name: api-container
    tty: true
    stdin_open: true
    volumes:
      - ./sharedrive:/shared
    networks:
      - worpress

  db-container:
    image: alpine:latest
    platform: linux/arm64
    container_name: db-container
    tty: true
    stdin_open: true
    volumes:
      - vol-db:/datos
    depends_on:
      - api-container
    networks:
      - worpress

volumes:
  sharedrive:
    driver: local
  vol-db:
    driver: local

networks:
  worpress:
    driver: bridge