services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - prueba
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - prueba

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - prueba

volumes:
  db_data:
    driver: local

networks:
  prueba:
    driver: bridge