name: Mi Primer CI/CD

on:
  push:
    branches: [week3]
#   pull_request:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Descargar código
        uses: actions/checkout@v4
      - name: 👋 ¡Hola mundo DevOps!
        run: |
            echo "¡Hola DevOps con Roxs! 🚀"
            date
            uname -a

      - name: 🧪 Test Matemático
        run: |
            if [ $((2+2)) -eq 4 ]; then
            echo "✅ Todo OK"
            else
            echo "❌ Algo falló"
            exit 1
            fi