name: Build Docker

on:
    push:
        branches: [week3]
#   pull_request:
#     branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11'

          - name: Install dependencies
            run: |
              pip install -r requirements.txt

          - name: Run tests
            run: |
              pytest tests/ -v

          - name: Run with coverage
            run: |
              pytest --cov=app --cov-report=term --cov-report=html

          - name: Check app running
            run: |
              timeout 10 python app.py &
              sleep 5
              curl -f http://localhost:5000/health

          - name: Save report
            uses: actions/upload-artifact@v4
            with:
              name: coverage-report
              path: htmlcov/
